name: Get All Data

on:
  issues:
  schedule:
    - cron: 0 13 * * *

jobs:
  Get_And_Extract_Data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Data
      run: |
        python getstocksinfo.py
    - name: Commit
      run: |
        git config --global user.email johnhaung@163.com
        git config --global user.name huanghaozi
        git add .
        git commit -m "UPDATE DATA by github actions" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
  Push_Data:
    runs-on: ubuntu-latest
    steps:
      - name: ServerChan Notify
        uses: yakumioto/serverchan-action@v1
        env:
          DATA_CT: ${{ cat todayData.txt }}
        with:
          # Secret key
          key: ${{ secrets.sckey }}
          # Message title
          text: 今日数据
          # Message content
          desp: $DATA_CT
  
