name: Get All Data

on:
  issues:
  schedule:
    - cron: 0 13 * * *

jobs:
  Get_And_Extract_Data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Data
      run: |
        python getstocksinfo.py
        python extractData.py
    - name: Read File to Var
      id: rdFile
      uses: juliangruber/read-file-action@v1.0.0
      with:
        path: ./todayData.txt
    - name: ServerChan Notify
      uses: yakumioto/serverchan-action@v1
      with:
        key: ${{ secrets.sckey }}
        text: 今日数据
        desp: ${{ steps.rdFile.outputs.content }}
    - name: Commit
      run: |
        git config --global user.email johnhaung@163.com
        git config --global user.name huanghaozi
        git add .
        git commit -m "UPDATE DATA by github actions" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
